openapi: 3.1.0
info:
  title: Forget Password
  version: '1.0'
servers:
- url: "https://{host}"
  variables:
    host:
      default: host
security:
- sec0: []
paths:
  /auth/v1/web/password/forget:
    post:
      summary: Forget Password
      description: "Lets you set a new password if the customer has lost or forgot\
        \ password. This is applicable only for brands for which password is enabled.\
        \ You need to first generate sessionId and then use it in password/forget.\
        \ After setting a new password, the customer customer needs to authenticate\
        \ again - \n\n1. Generate token, \n2. Generate OTP, and \n3. Validate OTP."
      operationId: forget-password
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - identifierType
              - identifierValue
              - brand
              - sessionId
              - password
              - confirmPassword
              properties:
                identifierType:
                  type: string
                  description: "Identifier used for token generation. Values: MOBILE,\
                    \ EMAIL, USERNAME."
                identifierValue:
                  type: string
                  description: Value of the specified identifierType.
                brand:
                  type: string
                  description: Name of the brand/org for which authentication needs
                    to be verified.
                deviceId:
                  type: string
                  description: Unique ID of the device used for changing password.
                    Applicable only for mobile app.
                sessionId:
                  type: string
                  description: Unique sessionId generated for the identifierType and
                    deviceId combination.
                password:
                  type: string
                  description: New password for the account.
                confirmPassword:
                  type: string
                  description: Reenter the new password.
            examples:
              Sample POST Body:
                value:
                  identifierType: USERNAME
                  identifierValue: '9940000000'
                  deviceId: deviceid1
                  brand: KANMODEMO
                  password: password1
                  confirmPassword: password1
                  sessionId: D-86c23a88-9062-473d-ab3a-9a27145bf321
      responses:
        '200':
          description: '200'
          content:
            application/json:
              examples:
                Sample response for mobile application:
                  value:
                    status:
                      success: true
                      code: 200
                      message: SUCCESS
                  summary: Sample response for mobile application
                Sample response for web application:
                  summary: Sample response for web application
                  value:
                    status:
                      success: true
                      code: 200
                      message: SUCCESS
              schema:
                type: object
                properties:
                  status:
                    type: object
                    properties:
                      success:
                        type: boolean
                        example: true
                        default: true
                      code:
                        type: integer
                        example: 200
                        default: 0
                      message:
                        type: string
                        example: SUCCESS
        '400':
          description: '400'
          content:
            application/json:
              examples:
                Result:
                  value: "{}"
              schema:
                type: object
                properties: {}
      deprecated: false
      x-readme:
        code-samples:
        - code: "curl --location 'https://eu.api.capillarytech.com/auth/v1/password/forget'\
            \ \\\n--header 'Accept: application/json' \\\n--header 'Content-Type:\
            \ application/json' \\\n--header 'accept: application/json' \\\n--data\
            \ '{\n    \"identifierType\": \"MOBILE\",\n    \"identifierValue\": \"\
            919999922332\",\n    \"password\": \"QWERTY12345\",\n    \"confirmPassword\"\
            : \"QWERTY12345\",\n    \"brand\": \"DocDemo\",\n    \"deviceId\": \"\
            123456785\",\n    \"sessionId\": \"P-d13b591a-b4ff-4b8d-ab0b-20be09b3272e\"\
            \n}'"
          language: shell
          name: Sample request for mobile application
        - code: "curl --location 'https://eu.api.capillarytech.com/auth/v1/web/password/forget'\
            \ \\\n--header 'Accept: application/json' \\\n--header 'Content-Type:\
            \ application/json' \\\n--header 'accept: application/json' \\\n--data\
            \ '{\n    \"identifierType\": \"MOBILE\",\n    \"identifierValue\": \"\
            919999922332\",\n    \"password\": \"QWERTY12345\",\n    \"confirmPassword\"\
            : \"QWERTY12345\",\n    \"brand\": \"DocDemo\",\n    \"deviceId\": \"\
            123456785\",\n    \"sessionId\": \"P-0b18c430-ed15-461c-8315-8c745f1f4ff2\"\
            \n}'"
          language: shell
          name: Sample request for web application
        samples-languages:
        - shell
components:
  securitySchemes:
    sec0:
      type: http
      scheme: basic
