openapi: 3.1.0
info:
  title: Generate Authentication Token
  version: '1.0'
servers:
- url: "https://{host}"
  variables:
    host:
      default: host
security:
- sec0: []
paths:
  /auth/v1/web/token/generate:
    post:
      summary: Generate Authentication Token
      description: Generate authentication for web application.
      operationId: generate-authentication-tokenapi
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - identifierType
              - password
              - confirmPassword
              - brand
              - deviceId
              - identifierValue
              properties:
                identifierType:
                  type: string
                  description: Identifier used for token generation
                  enum:
                  - MOBILE
                  - EMAIL
                  - USERNAME.
                mobile:
                  type: string
                  description: Mobile number of the customer. Either mobile number
                    or email ID is required to authenticate with username.
                email:
                  type: string
                  description: Email ID of the customer. Either mobile number or email
                    ID is required to authenticate with username.
                password:
                  type: string
                  description: Password to login to the app.
                confirmPassword:
                  type: string
                  description: Reenter the password.
                brand:
                  type: string
                  description: Name of the brand/org for which authentication needs
                    to be verified.
                deviceId:
                  type: string
                  description: Unique ID of the device from which the customer has
                    generated the token.
                identifierValue:
                  type: string
                  description: Identifier value
            examples:
              Authenticate with mobile/email:
                value:
                  identifierType: MOBILE
                  identifierValue: 0495678923
                  deviceId: deviceid1
                  brand: STANDARDAPP
      responses:
        '200':
          description: '200'
          content:
            application/json:
              examples:
                Result:
                  value: "{\n    \"status\": {\n        \"success\": true,\n     \
                    \   \"code\": 200,\n        \"message\": \"SUCCESS\"\n    },\n\
                    \    \"auth\": {\n        \"token\": \"eyJpZHYiOlsiTU9CSUxFfDk5NDU1NjAyMjQiXSwiZGV2IjoiMzJydHNkZXJlZCIsIm9yZyI6IlNUQU5EQVJEQVBQIiwiYWxnIjoiSFMyNTYifQ.eyJpc3MiOiJDQVBJTExBUlkgVEVDSE5PTE9HSUVTIiwib2djIjpbIjE1MTA2MHxzYS5kZW1vLnNvbHV0aW9uIl0sImV4cCI6MTU5NzY1NTgxMywiaWF0IjoxNTk3NjUyMjEzLCJyb2wiOiJWSUVXIn0.2LqAg3tDVu8VwasSXuwiL6p917NCxgpKEt76qqrARgQ\"\
                    ,\n        \"key\": null\n    },\n    \"user\": {\n        \"\
                    appRegistered\": false,\n        \"sessionId\": \"D-12c177af-dac7-4383-a0fb-6c09e148af8e\"\
                    ,\n        \"role\": \"VIEW\",\n        \"userRegisteredForPassword\"\
                    : false\n    }\n}"
                Sample response for existing user:
                  summary: Sample response for existing user
                  value:
                    status:
                      success: true
                      code: 200
                      message: SUCCESS
                    auth:
                      token: eyJpZHYiOlsiTU9CSUxFfDkxOTk5OTk5OTk5MyJdLCJkZXYiOiIxMjM0NTY3ODUiLCJvcmciOiJET0NERU1PIiwiYWxnIjoiSFMyNTYifQ.eyJpc3MiOiJDQVBJTExBUlkgVEVDSE5PTE9HSUVTIiwib2djIjpbIjEwMDczN3xuZWVyYWouZG9jIl0sImV4cCI6MTc1OTgzOTMzNSwiaWF0IjoxNzU5ODM1NzM1LCJyb2wiOiJWSUVXIn0.8gRfA0CdBjYuSLtNJwREvmYqaAtk9C0Zm-b_-gUqPNQ
                      key: null
                    user:
                      appRegistered: false
                      sessionId: P-6ec5fcc9-2bca-4778-9672-4ee5097d8313
                      role: VIEW
                      userRegisteredForPassword: true
                Sample response for first time user when password is enabled:
                  summary: Sample response for first time user when password is enabled
                  value:
                    status:
                      success: true
                      code: 200
                      message: SUCCESS
                    auth:
                      token: eyJpZHYiOlsiTU9CSUxFfDkxOTk5OTk5OTk5MSJdLCJkZXYiOiIxMjM0NTY3ODUiLCJvcmciOiJET0NERU1PIiwiYWxnIjoiSFMyNTYifQ.eyJpc3MiOiJDQVBJTExBUlkgVEVDSE5PTE9HSUVTIiwib2djIjpbIjEwMDczN3xuZWVyYWouZG9jIl0sImV4cCI6MTc1OTg0MTQxOSwiaWF0IjoxNzU5ODM3ODE5LCJyb2wiOiJWSUVXIn0.e1bltp_Tl7v4lBe0wRDH75NEPqmBcJBfZmFMdX9K-5s
                      key: null
                    user:
                      appRegistered: false
                      sessionId: P-4b9437d5-38fe-4252-9628-9960f9b221f8
                      role: VIEW
                      userRegisteredForPassword: false
                For existing user using web app:
                  summary: For existing user using web app
                  value:
                    status:
                      success: true
                      code: 200
                      message: SUCCESS
                    auth:
                      token: eyJpZHYiOlsiRU1BSUx8Y2FwdGVzdEBnbWFpbC5jb20iXSwiZGV2IjpudWxsLCJvcmciOiJET0NERU1PIiwiYWxnIjoiSFMyNTYifQ.eyJpc3MiOiJDQVBJTExBUlkgVEVDSE5PTE9HSUVTIiwib2djIjpbIjEwMDczN3xuZWVyYWouZG9jIl0sImV4cCI6MTc1OTgzODgyNSwiaWF0IjoxNzU5ODM4NzM1LCJyb2wiOiJWSUVXIn0.2r1IueohKRA5dUmcWL23Ue1dCbcRDCrTKmaZGdPKABU
                      key: null
                    user:
                      appRegistered: false
                      sessionId: P-a7f12cf8-8f64-4d74-87c1-644fdf67ef58
                      role: VIEW
                      userRegisteredForPassword: true
                First time user when password is enabled and using web app:
                  summary: First time user when password is enabled and using web
                    app
                  value:
                    status:
                      success: true
                      code: 200
                      message: SUCCESS
                    auth:
                      token: eyJpZHYiOlsiRU1BSUx8Y2FwX3Rlc3R0b2tlbmdlbkBnbWFpbC5jb20iXSwiZGV2IjpudWxsLCJvcmciOiJET0NERU1PIiwiYWxnIjoiSFMyNTYifQ.eyJpc3MiOiJDQVBJTExBUlkgVEVDSE5PTE9HSUVTIiwib2djIjpbIjEwMDczN3xuZWVyYWouZG9jIl0sImV4cCI6MTc1OTgzOTM5MywiaWF0IjoxNzU5ODM5MzAzLCJyb2wiOiJWSUVXIn0.t38TrWnszJrlEo2E4Amq91O54VOe7CED-OOQkNjK80w
                      key: null
                    user:
                      appRegistered: false
                      sessionId: P-99bfa3b8-10bf-4f39-a705-333bd1ca10d1
                      role: VIEW
                      userRegisteredForPassword: false
              schema:
                type: object
                properties:
                  status:
                    type: object
                    properties:
                      success:
                        type: boolean
                        example: true
                        default: true
                      code:
                        type: integer
                        example: 200
                        default: 0
                      message:
                        type: string
                        example: SUCCESS
                  auth:
                    type: object
                    properties:
                      token:
                        type: string
                        example: eyJpZHYiOlsiTU9CSUxFfDk5NDU1NjAyMjQiXSwiZGV2IjoiMzJydHNkZXJlZCIsIm9yZyI6IlNUQU5EQVJEQVBQIiwiYWxnIjoiSFMyNTYifQ.eyJpc3MiOiJDQVBJTExBUlkgVEVDSE5PTE9HSUVTIiwib2djIjpbIjE1MTA2MHxzYS5kZW1vLnNvbHV0aW9uIl0sImV4cCI6MTU5NzY1NTgxMywiaWF0IjoxNTk3NjUyMjEzLCJyb2wiOiJWSUVXIn0.2LqAg3tDVu8VwasSXuwiL6p917NCxgpKEt76qqrARgQ
                      key: {}
                  user:
                    type: object
                    properties:
                      appRegistered:
                        type: boolean
                        example: false
                        default: true
                      sessionId:
                        type: string
                        example: D-12c177af-dac7-4383-a0fb-6c09e148af8e
                      role:
                        type: string
                        example: VIEW
                      userRegisteredForPassword:
                        type: boolean
                        example: false
                        default: true
        '400':
          description: '400'
          content:
            application/json:
              examples:
                Result:
                  value: "{}"
              schema:
                type: object
                properties: {}
      deprecated: false
      x-readme:
        code-samples:
        - language: shell
          code: "curl --location 'https://eu.api.capillarytech.com/auth/v1/web/token/generate'\
            \ \\\n--header 'Accept: application/json' \\\n--header 'Content-Type:\
            \ application/json' \\\n--data '{\n   \"identifierType\":\"USERNAME\"\
            ,\n   \"identifierValue\":\"9945560224\",\n   \"mobile\":\"9988221100\"\
            ,\n   \"email\": \"\",\n    \"deviceId\": \"deviceid1\",\n    \"brand\"\
            : \"STANDARDAPP\",\n    \"password\":\"password\",\n    \"confirmPassword\"\
            :\"password\"\n}'"
          name: Authenticate with username
        - code: "curl --location 'https://eu.api.capillarytech.com/auth/v1/token/generate'\
            \ \\\n--header 'Accept: application/json' \\\n--header 'Content-Type:\
            \ application/json' \\\n--header 'accept: application/json' \\\n--header\
            \ 'Cookie: _cfuvid=r0qUeHW4DtOxdgIN8.dJs77Xj15OkoCeaHRiplR4Qxs-1759834804501-0.0.1.1-604800000'\
            \ \\\n--data '{\n    \"identifierType\": \"MOBILE\",\n    \"identifierValue\"\
            : \"919999999993\",\n    \"brand\": \"DocDemo\",\n    \"deviceId\": \"\
            123456785\"\n}'"
          language: shell
          name: For existing user - Mobile app
        - code: "curl --location 'https://eu.api.capillarytech.com/auth/v1/token/generate'\
            \ \\\n--header 'Accept: application/json' \\\n--header 'Content-Type:\
            \ application/json' \\\n--header 'accept: application/json' \\\n--header\
            \ 'Cookie: _cfuvid=r0qUeHW4DtOxdgIN8.dJs77Xj15OkoCeaHRiplR4Qxs-1759834804501-0.0.1.1-604800000'\
            \ \\\n--data '{\n    \"identifierType\": \"MOBILE\",\n    \"identifierValue\"\
            : \"919999999991\",\n    \"brand\": \"DocDemo\",\n    \"deviceId\": \"\
            123456785\",\n    \"password\" : \"abc123\",\n    \"confirmPassword\"\
            \ : \"abc123\"\n}'"
          language: shell
          name: For first time user when password authentication is enabled
        - code: "curl --location 'https://eu.api.capillarytech.com/auth/v1/web/token/generate'\
            \ \\\n--header 'Accept: application/json' \\\n--header 'Content-Type:\
            \ application/json' \\\n--header 'accept: application/json' \\\n--header\
            \ 'Cookie: _cfuvid=dx9m0omOPswla2ni.yXNOV.9_4qHLCcfMI_vqjitSvU-1759835382650-0.0.1.1-604800000;\
            \ _cfuvid=r0qUeHW4DtOxdgIN8.dJs77Xj15OkoCeaHRiplR4Qxs-1759834804501-0.0.1.1-604800000'\
            \ \\\n--data-raw '\n{\n  \"identifierType\": \"EMAIL\",\n   \"identifierValue\"\
            : \"captest@gmail.com\",\n    \"brand\": \"DocDemo\"\n}\n'"
          language: shell
          name: For existing user using web app
        - code: "curl --location 'https://eu.api.capillarytech.com/auth/v1/web/token/generate'\
            \ \\\n--header 'Accept: application/json' \\\n--header 'Content-Type:\
            \ application/json' \\\n--header 'accept: application/json' \\\n--header\
            \ 'Cookie: _cfuvid=dx9m0omOPswla2ni.yXNOV.9_4qHLCcfMI_vqjitSvU-1759835382650-0.0.1.1-604800000;\
            \ _cfuvid=r0qUeHW4DtOxdgIN8.dJs77Xj15OkoCeaHRiplR4Qxs-1759834804501-0.0.1.1-604800000'\
            \ \\\n--data-raw '\n{\n  \"identifierType\": \"EMAIL\",\n   \"identifierValue\"\
            : \"cap_testtokengen@gmail.com\",\n    \"brand\": \"DocDemo\",\n    \"\
            password\" : \"abc123\",\n    \"confirmPassword\" : \"abc123\"\n}\n'"
          language: shell
          name: First time user when password is enabled and using web app
        samples-languages:
        - shell
components:
  securitySchemes:
    sec0:
      type: http
      scheme: basic
