openapi: 3.1.0
info:
  title: Validate OTP
  version: '1.0'
servers:
- url: "https://{host}"
  variables:
    host:
      default: host
security:
- sec0: []
paths:
  /auth/v1/web/otp/validate:
    post:
      summary: Validate OTP
      description: Validates the OTP generated through the `/otp/generate` API.
      operationId: validate-otp-api
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - identifierType
              - identifierValue
              - brand
              - deviceId
              - sessionId
              - otp
              properties:
                identifierType:
                  type: string
                  description: "Identifier used for token generation. Values: MOBILE,\
                    \ EMAIL, USERNAME."
                identifierValue:
                  type: string
                  description: Value of the specified identifierType.
                brand:
                  type: string
                  description: Name of the brand/org for which authentication needs
                    to be verified.
                deviceId:
                  type: string
                  description: Unique ID of the device from which the customer has
                    generated the token.
                sessionId:
                  type: string
                  description: Session ID generated through the `v1/token/generate`
                    API.
                otp:
                  type: string
                  description: Validation code received by the customer.
            examples:
              Sample POST Body:
                value:
                  identifierType: MOBILE
                  identifierValue: '9940000000'
                  deviceId: deviceid1
                  brand: standardapp
                  sessionId: D-502259d3-d4d6-4458-bc5f-b89d3d8e4c7b
                  otp: '276889'
      responses:
        '200':
          description: '200'
          content:
            application/json:
              examples:
                Sample response using mobile application:
                  value:
                    status:
                      success: true
                      code: 200
                      message: SUCCESS
                    auth:
                      token: eyJpZHYiOlsiTU9CSUxFfDkxOTk5OTk5OTk5MyJdLCJkZXYiOiIxMjM0NTY3ODUiLCJvcmciOiJET0NERU1PIiwiYWxnIjoiSFMyNTYifQ.eyJ1aWQiOiI0MDQ4NjQ3IiwiaXNzIjoiQ0FQSUxMQVJZIFRFQ0hOT0xPR0lFUyIsImlzYyI6ImZhbHNlIiwib2djIjpbIjEwMDczN3xuZWVyYWouZG9jIl0sImV4cCI6MTc2MDAxNzA4MCwiaWF0IjoxNzYwMDEzNDgwLCJyb2wiOiJVU0VSIn0.8cNCH_T63gDOE4BP9QoRT96eOs-qYlUVpO5MrVJwJPo
                      key: eyJpZHYiOlsiTU9CSUxFfDkxOTk5OTk5OTk5MyJdLCJkZXYiOiIxMjM0NTY3ODUiLCJvcmciOiJET0NERU1PIiwiYWxnIjoiSFMyNTYifQ.eyJ1aWQiOiI0MDQ4NjQ3IiwiaXNzIjoiQ0FQSUxMQVJZIFRFQ0hOT0xPR0lFUyIsImlhdCI6MTc2MDAxMzQ4MCwicm9sIjoiQVVUSCJ9.YbMefn1HT8kkHb1r9hTRyAU-Uf3R-rNpJPlShFa0o4k
                    user:
                      appRegistered: false
                      sessionId: null
                      role: USER
                      userRegisteredForPassword: true
                  summary: Sample response using mobile application
                Sample response using web application:
                  summary: Sample response using web application
                  value:
                    status:
                      success: true
                      code: 200
                      message: SUCCESS
                    auth:
                      token: eyJpZHYiOlsiRU1BSUx8Y2FwdGVzdEBnbWFpbC5jb20iXSwiZGV2IjpudWxsLCJvcmciOiJET0NERU1PIiwiYWxnIjoiSFMyNTYifQ.eyJ1aWQiOiI0MDY4MjkxIiwiaXNzIjoiQ0FQSUxMQVJZIFRFQ0hOT0xPR0lFUyIsImlzYyI6ImZhbHNlIiwib2djIjpbIjEwMDczN3xuZWVyYWouZG9jIl0sImV4cCI6MTc2MDAxMzg0MywiaWF0IjoxNzYwMDEzNzUzLCJyb2wiOiJVU0VSIn0.N7ocUUT5eBXE-rRIoJvRWmMIEN56CIr8_NXQYkUGYig
                      key: null
                    user: null
              schema:
                type: object
                properties:
                  status:
                    type: object
                    properties:
                      success:
                        type: boolean
                        example: true
                        default: true
                      code:
                        type: integer
                        example: 200
                        default: 0
                      message:
                        type: string
                        example: SUCCESS
                  auth:
                    type: object
                    properties:
                      token:
                        type: string
                        example: eyJpZHYiOlsiTU9CSUxFfDk5NDU1NjAyMjQiXSwiZGV2IjoiZGV2aWNlaWQxIiwib3JnIjoiU1RBTkRBUkRBUFAiLCJhbGciOiJIUzI1NiJ9.eyJ1aWQiOiI3Njg4MTYiLCJpc3MiOiJDQVBJTExBUlkgVEVDSE5PTE9HSUVTIiwiaXNjIjoiZmFsc2UiLCJvZ2MiOlsiMTUxMDYwfHNhLmRlbW8uc29sdXRpb24iXSwiZXhwIjoxNTk3OTQzODU1LCJpYXQiOjE1OTc5NDAyNTUsInJvbCI6IlVTRVIifQ.Wyt_xxlqtmMH3lyReO718sDokngYGp_HSLuiBOyaEds
                      key:
                        type: string
                        example: eyJpZHYiOlsiTU9CSUxFfDk5NDU1NjAyMjQiXSwiZGV2IjoiZGV2aWNlaWQxIiwib3JnIjoiU1RBTkRBUkRBUFAiLCJhbGciOiJIUzI1NiJ9.eyJ1aWQiOiI3Njg4MTYiLCJpc3MiOiJDQVBJTExBUlkgVEVDSE5PTE9HSUVTIiwiaWF0IjoxNTk3OTQwMjU1LCJyb2wiOiJBVVRIIn0.UKCOU1oFLPsRx5YJRkClIaRVmE1lNDCjuuKQ9nnMdhE
                  user:
                    type: object
                    properties:
                      appRegistered:
                        type: boolean
                        example: false
                        default: true
                      sessionId: {}
                      role:
                        type: string
                        example: USER
                      userRegisteredForPassword:
                        type: boolean
                        example: false
                        default: true
        '400':
          description: '400'
          content:
            application/json:
              examples:
                Result:
                  value: "{}"
              schema:
                type: object
                properties: {}
      deprecated: false
      x-readme:
        code-samples:
        - code: "curl --location 'https://eu.api.capillarytech.com/auth/v1/otp/validate'\
            \ \\\n--header 'Accept: application/json' \\\n--header 'Content-Type:\
            \ application/json' \\\n--header 'accept: application/json' \\\n--header\
            \ 'Cookie: _cfuvid=4cDcLYjTxIP0ezb6fRYB0epcC4lTjAo5Uwd.pLnw9Ag-1760013365505-0.0.1.1-604800000'\
            \ \\\n--data '{\n    \"identifierType\": \"MOBILE\",\n    \"identifierValue\"\
            : \"919999999993\",\n    \"brand\": \"DocDemo\",\n    \"deviceId\": \"\
            123456785\",\n    \"sessionId\": \"P-6e195d03-a643-4d24-bbda-0d6e3810b06d\"\
            ,\n    \"otp\": \"999999\"\n}'"
          language: shell
          name: Sample request using mobile application
        - code: "curl --location 'https://eu.api.capillarytech.com/auth/v1/web/otp/validate'\
            \ \\\n--header 'Accept: application/json' \\\n--header 'Content-Type:\
            \ application/json' \\\n--header 'accept: application/json' \\\n--header\
            \ 'Cookie: _cfuvid=XCyqCZlwYDamaqrRf8xpmEpz1ZwdbLmtWOS4zHmfliY-1760013652075-0.0.1.1-604800000'\
            \ \\\n--data-raw '{\n    \"identifierType\": \"EMAIL\",\n    \"identifierValue\"\
            : \"captest@gmail.com\",\n    \"brand\": \"DocDemo\",\n   \n    \"sessionId\"\
            : \"P-db0a6a4b-14e9-4b0b-998e-72203c39aa45\",\n    \"otp\": \"999999\"\
            \n}'"
          language: shell
          name: Sample request using web application
        samples-languages:
        - shell
components:
  securitySchemes:
    sec0:
      type: http
      scheme: basic
